// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe0MfN3ieDaEmoc7_rnCtpTfrS-OoE_K4',
    appId: '1:346481897314:web:ae9da1ab10df121563463b',
    messagingSenderId: '346481897314',
    projectId: 'bus-trax',
    authDomain: 'bus-trax.firebaseapp.com',
    databaseURL: 'https://bus-trax-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-trax.firebasestorage.app',
    measurementId: 'G-0B8207HKTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASYGJ7NgCFdH0ObYxjfYDiCkDyy0I9lFU',
    appId: '1:346481897314:android:291b555bc2e7904e63463b',
    messagingSenderId: '346481897314',
    projectId: 'bus-trax',
    databaseURL: 'https://bus-trax-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-trax.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMtiZ_fgixZ44AxgQipZsEreccFIxv5kE',
    appId: '1:346481897314:ios:b8ce96c5a8638a1c63463b',
    messagingSenderId: '346481897314',
    projectId: 'bus-trax',
    databaseURL: 'https://bus-trax-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-trax.firebasestorage.app',
    iosBundleId: 'com.example.busTrax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMtiZ_fgixZ44AxgQipZsEreccFIxv5kE',
    appId: '1:346481897314:ios:b8ce96c5a8638a1c63463b',
    messagingSenderId: '346481897314',
    projectId: 'bus-trax',
    databaseURL: 'https://bus-trax-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-trax.firebasestorage.app',
    iosBundleId: 'com.example.busTrax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe0MfN3ieDaEmoc7_rnCtpTfrS-OoE_K4',
    appId: '1:346481897314:web:68ba7c9bd88bd31963463b',
    messagingSenderId: '346481897314',
    projectId: 'bus-trax',
    authDomain: 'bus-trax.firebaseapp.com',
    databaseURL: 'https://bus-trax-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-trax.firebasestorage.app',
    measurementId: 'G-FKTESTNYM4',
  );
}
